INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Pad Thai', 'Popular thai dish.', 25,'https://images.ctfassets.net/uexfe9h31g3m/3HRQmwGA3Ke4y8ukoy4aEk/e7da70846538442c4cb3fd8fcd9dcc96/PadThai_1024x768.jpg?w=1024&h=768&fm=webp&fit=thumb&q=90', 'Phone nr: 12345678, email: Brigitte@mail.com', 'Asian');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Carbonara', 'Italian pasta dish.', 25,'https://www.kikkoman.dk/fileadmin/_processed_/6/6/csm_WEB_Mushroom_Carbonara_b1414b0714.jpg', 'Phone nr: 12345678, email: Brigitte@mail.com', 'Italian');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Meatloaf', 'American meatloaf - a mixture of ground pork and cornmeal.', 25, 'https://voresmad.dk/-/media/voresmad/recipes/f/forlorenhare-traditionel1.jpg?h=503&iar=0&w=900&hash=ADA68BF8517C585C2414323E57972623', 'Phone nr: 12345678, email: Brigitte@mail.com','American');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Wok with Chicken', 'Homemade wok with chicken, rice and brocolli. The wok contains nuts, so not very suitable for people with allergies', 25, 'https://cdn.tourismontheedge.com/wp-content/uploads/2021/09/food-rice.jpg', 'Phone nr: 12345678, email: Brigitte@mail.com','Asian');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Mashed Potatoes with peas and beans', 'Homemade mashed potatoes, made with potatoes from my own garden, and ecologic milk', 25, 'https://marleyspoon.com/media/recipes/61290/main_photos/large/cranberry_glazed_turkey_meatloaf-5ddb0aba9d5d4d0a2394945f436f4c80.jpeg', 'Phone nr: 12345678, email: Brigitte@mail.com','Classic danish');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Tortilla with everything, ready and packed', ' I have made tortillas, but ended up with a lot of leftovers. It is packed and ready for take away', 25, 'https://www.nammadabba.com/images/vendor/1621533179.jpg', 'Phone nr: 12345678, email: Brigitte@mail.com','');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Couscous with greens', 'Great for the vegan who loves great food', 25, 'https://images.immediate.co.uk/production/volatile/sites/30/2018/06/Vegan-salad-bowl-499145d.jpg?quality=90&resize=556,505', 'Phone nr: 12345678, email: Brigitte@mail.com','Vegan');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Vegetarian Paella', 'Made it with my friends great recipe', 25, 'https://images.immediate.co.uk/production/volatile/sites/2/2020/05/olive_GoldenOnionPilaf_preview-b26daf2.jpg?quality=90&resize=556,505', 'Phone nr: 12345678, email: Brigitte@mail.com','Vegetarian');
INSERT INTO Meal (name, description, price, img, contact, tag) VALUES ('Homemade Tapas', 'Great as both a snack or a delicious meal', 25, 'https://i0.wp.com/spainonafork.com/wp-content/uploads/2020/01/tapas1-11blog.png?fit=750%2C750&ssl=1', 'Phone nr: 12345678, email: Brigitte@mail.com','Tapas');


INSERT INTO USER_PROFILE (name, username, password, email, address, phone, country, postcode) VALUES('Lisa', 'Lisa', '123', 'Lisa@AW-mail.dk', '32 cph c', '12345678', 'Denmark', '1234');
INSERT INTO USER_PROFILE (name, username, password, email, address, phone, country, postcode) VALUES('Sion', 'Sion', '123', 'Sion@AW-mail.dk', '32 cph c', '12345678', 'Denmark', '1234');
INSERT INTO USER_PROFILE (name, username, password, email, address, phone, country, postcode) VALUES('Johnny', 'Johnny', '123', 'Johnny@AW-mail.dk', '32 cph c', '12345678', 'Denmark', '1234');

