CREATE TABLE Meal(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(MAX),
  price BIGINT NOT NULL,
  link VARCHAR(MAX)

);

CREATE TABLE USER_PROFILE(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(64) NOT NULL,
username VARCHAR(64),
password VARCHAR(64)
);