CREATE TABLE createAMeal(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(MAX),
  price BIGINT NOT NULL,
  link VARCHAR(MAX),
  img VARCHAR(MAX)
);

CREATE TABLE createUser(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64),
  password VARCHAR(64)
);